services:
  web:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env:/src/PROJ/.env
    restart: unless-stopped
    depends_on:
      - pgsql
      - redis

  pgsql:
    image: postgres:16-alpine
    container_name: pg
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    restart: unless-stopped
  
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  pgdata:
